# Tensor product

Kronecker tensor product of two or more matrices.

## Example

In [3]:
from toqito.base.ket import ket
from toqito.matrix.operations.tensor import tensor, tensor_n, tensor_list
import numpy as np

### Tensor product two matrices or vectors

Consider the following ket vector

$$
|0 \rangle = \left[1, 0 \right]^{\text{T}}
$$

Computing the following tensor product 

$$
|0 \rangle \otimes |0 \rangle = \left[1, 0, 0, 0 \right]^{\text{T}}
$$

This can be accomplished in `toqito` as follows.

In [4]:
e_0 = ket(2, 0)
tensor(e_0, e_0)

array([[1],
       [0],
       [0],
       [0]])

### Tensor product one matrix `n` times with itself.

We may also tensor some element with itself some integer number of times. For instance we can compute

$$
|0 \rangle^{\otimes 3} = \left[1, 0, 0, 0, 0, 0, 0, 0 \right]^{\text{T}}
$$

in `toqito` as follows.

In [6]:
e_0 = ket(2, 0)
tensor_n(e_0, 3)

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

### Perform the tensor product on a list of vectors or matrices.

If we wish to compute the tensor product against more than two matrices or vectors, we can feed them in as a `list`. For instance, if we wish to compute $|0 \rangle \otimes |1 \rangle \otimes |0 \rangle$, we can do so as follows.

In [7]:
e_0, e_1 = ket(2, 0), ket(2, 1)
tensor_list([e_0, e_1, e_0])

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0]])

## References

[1] Wikipedia: Tensor product
        https://en.wikipedia.org/wiki/Tensor_product
