# Conclusive state exclusion

Compute probability of conclusive single state exclusion.

The "quantum state exclusion" problem involves a collection of $n$ quantum states

$$
        \rho = \{ \rho_0, \ldots, \rho_n \},
$$

as well as a list of corresponding probabilities

$$
        p = \{ p_0, \ldots, p_n \}
$$        

Alice chooses $i$ with probability $p_i$ and creates the state $\rho_i$.

Bob wants to guess which state he was *not* given from the collection of states. State exclusion implies that ability to discard (with certainty) at least one out of the "n" possible quantum states by applying a measurement.

This function implements the following semidefinite program that provides the optimal probability with which Bob can conduct quantum state exclusion.

$$
            \begin{equation}
                \begin{aligned}
                    \text{minimize:} \quad & \sum_{i=0}^n p_i \langle M_i,
                                                \rho_i \rangle \\
                    \text{subject to:} \quad & M_0 + \ldots + M_n =
                                               \mathbb{I}, \\
                                             & M_0, \ldots, M_n >= 0
                \end{aligned}
            \end{equation}
$$

## Examples

In [3]:
from toqito.state.optimizations.conclusive_state_exclusion import conclusive_state_exclusion
from toqito.state.states.bell import bell
import numpy as np

X

In [6]:
        """State exclusion for three Bell state density matrices."""
        rho1 = bell(0) * bell(0).conj().T
        rho2 = bell(1) * bell(1).conj().T
        rho3 = bell(2) * bell(2).conj().T
        states = [rho1, rho2, rho3]
        probs = [1 / 3, 1 / 3, 1 / 3]

conclusive_state_exclusion(states, probs)

1.6824720366521913e-09

By specifying the `sys = 1` argument, we can perform the partial trace over the first subsystem (instead of the default second subsystem as done above). Performing the partial trace over the first subsystem yields the following matrix

$$
X_{pt, 1} = \begin{pmatrix}
                12 & 14 \\
                20 & 22
            \end{pmatrix}
$$

In [5]:
test_input_mat = np.array(
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
)
partial_trace(test_input_mat, 1)

array([[12, 14],
       [20, 22]])

We can also specify both dimension and system size as `list` arguments. Consider the following $16$-by-$16$ matrix.

In [8]:
"""16-by-16 matrix."""
test_input_mat = np.arange(1, 257).reshape(16, 16)
print(test_input_mat)

[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16]
 [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32]
 [ 33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48]
 [ 49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64]
 [ 65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112]
 [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128]
 [129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144]
 [145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176]
 [177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192]
 [193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208]
 [209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224]
 [225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 

We can take the partial trace on the first and third subsystems and assume that the size of each of the 4 systems is of dimension 2.

In [9]:
partial_trace(test_input_mat, [1, 3], [2, 2, 2, 2])

array([[344, 348, 360, 364],
       [408, 412, 424, 428],
       [600, 604, 616, 620],
       [664, 668, 680, 684]])

## References

[1] Wikipedia: Partial trace
        https://en.wikipedia.org/wiki/Partial_trace