# Schmidt decomposition

Compute the Schmidt decomposition of a bipartite vector.

## Examples

In [4]:
from toqito.state.states.max_entangled import max_entangled
from toqito.state.operations.schmidt_decomposition import schmidt_decomposition
import numpy as np

Consider the $3$-dimensional maximally entangled state

$$
u = \frac{1}{\sqrt{3}} \left( |000> + |111> + |222> \right)
$$

We can generate this state using the `toqito` module as follows.

In [12]:
max_entangled(3)

array([[0.57735027],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.57735027],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.57735027]])

Computing the Schmidt decomposition of $u$, we can obtain the corresponding singular values of $u$ as 

$$
\frac{1}{\sqrt{3}} \left[1, 1, 1 \right]^{\text{T}}
$$

In [14]:
"""Schmidt decomposition of the 3-D maximally entangled state."""
singular_vals, u_mat, vt_mat = schmidt_decomposition(max_entangled(3))

In [8]:
print(singular_vals)

[[0.57735027]
 [0.57735027]
 [0.57735027]]


In [9]:
print(u_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
print(vt_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## References

[1] Wikipedia: Schmidt decomposition
        https://en.wikipedia.org/wiki/Schmidt_decomposition